# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxhunt.dev/"
  version "4.40.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-cat.1"
  manpage "fox-check.1"
  manpage "fox-dump.1"
  manpage "fox-hash.1"
  manpage "fox-hex.1"
  manpage "fox-hunt.1"
  manpage "fox-stat.1"
  manpage "fox-str.1"
  manpage "fox.1"

  on_macos do
    on_intel do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "72ab68ba7a6f94fe97d3f1b858f5b3b42e3166ac870466d9a42db33304471bdc"
    end
    on_arm do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "677baac05a71bc10e989669dbfe1826a0483f9e133fbc220b795349a69206293"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "7330eeb200c926542a233d1e91d94d17774e841fd2f8efbf5a4e9741b93af78f"
    end
    on_arm do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "2934c68eeefb295233de65807ea132a59e58d40b356aa80dc7a25a881d80c063"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required
end
