# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxhunt.dev/"
  version "4.41.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-dump.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox.1"

  on_macos do
    on_intel do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "28824f6f4afbab77114e02ab6529b7c342b0f758c384a1106eeeffa98919b2af"
    end
    on_arm do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "12cc82651812af777c769ef4e9dc8703c43b50c0dac937ca40e3bd1f16263520"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "088c74c3a43681e79a66224800934ad3ff6c4bb5562ec17d95325cbac168edb3"
    end
    on_arm do
      url "https://github.com/cuhsat/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/cuhsat/homebrew-fox/"
      sha256 "83b25b63bee939b01598a74b65ec12ed16eaa307b42a37bcfbbb619cab1754bd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required
end
