# This file was generated by GoReleaser. DO NOT EDIT.
cask "fox" do
  name "fox"
  desc "The Forensic Examiners Swiss Army Knife"
  homepage "https://foxforensics.dev/"
  version "4.44.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fox"
  manpage "fox-dump.1"
  manpage "fox-hash.1"
  manpage "fox-hunt.1"
  manpage "fox-info.1"
  manpage "fox-str.1"
  manpage "fox.1"

  on_macos do
    on_intel do
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_darwin_amd64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
      sha256 "bc2dec3cbf1cc0fa60b737778a2f06f812ffda4f4dd8223654816b9a542652e8"
    end
    on_arm do
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_darwin_arm64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
      sha256 "6e60b8a364c14d97b5ca13bd155b7ac9781d470f4a5f9e595434259a12e1ff67"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_linux_amd64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
      sha256 "b73dd2300fbebbd06ae94e2c989802ed0695ddb10c1b8121780d599c2fd79f89"
    end
    on_arm do
      url "https://github.com/f0x4n6/fox/releases/download/v#{version}/fox_linux_arm64.tar.gz",
        verified: "github.com/f0x4n6/fox-cask/"
      sha256 "841e4fcb2044cb91424bb162d005f88793ad9882122f05ec2f25aecc681e05fa"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fox"]
    end
  end

  # No zap stanza required
end
